# Generated by Django 3.2.3 on 2021-06-22 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Genero')),
                ('nombreGenero', models.CharField(max_length=50, verbose_name='Nombre de Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('titulo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Titulo de la pelicula')),
                ('protagonista', models.CharField(max_length=50, verbose_name='Protagonista de la pelicula')),
                ('sinopsis', models.CharField(max_length=300, verbose_name='Sinopsis de la pelicula')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genero')),
            ],
        ),
    ]
